picUrl="/opt/pictures"
 spring:
   data:
     mongodb:
       host: 127.0.0.1
       database: local
   http:
     multipart:
       max-file-size: 100Mb
       max-request-size: 100Mb
server:
  context-path: /alice

